sample_read1: "/path/to/sample/sample_R1.fastq"
samplesheet: "/path/to/sample/sample_samplesheet.txt"
barcodefile:  "~/gbs/GBS_snakemake_pipeline/workflow/resources/barcodes/barcodes_192.txt"
reference_file: "/path/to/reference.fasta"